// <auto-generated />
namespace ActivityManagement.Infrastructure.Persistence.Migrations;

using ActivityManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

[DbContext(typeof(ActivityManagementDbContext))]
partial class ActivityManagementDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.6")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("ActivityManagement.Domain.Activities.Activity", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<Guid?>("AccountLink")
                .HasColumnType("uuid")
                .HasColumnName("account_id");

            b.Property<Guid>("BuId")
                .HasColumnType("uuid")
                .HasColumnName("bu_id");

            b.Property<DateTimeOffset?>("CompletedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("completed_at");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<string>("Description")
                .HasColumnType("text")
                .HasColumnName("description");

            b.Property<DateTimeOffset>("DueAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("due_at");

            b.Property<Guid>("OwnerId")
                .HasColumnType("uuid")
                .HasColumnName("owner_id");

            b.Property<Guid?>("OpportunityLink")
                .HasColumnType("uuid")
                .HasColumnName("opportunity_id");

            b.Property<string>("Priority")
                .IsRequired()
                .HasMaxLength(10)
                .HasDefaultValue("medium")
                .HasColumnType("character varying(10)")
                .HasColumnName("priority");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("pending")
                .HasColumnType("character varying(20)")
                .HasColumnName("status");

            b.Property<Guid>("TenantId")
                .HasColumnType("uuid")
                .HasColumnName("tenant_id");

            b.Property<string>("Title")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("title");

            b.Property<string>("Type")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)")
                .HasColumnName("activity_type");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.HasKey("Id");

            b.ToTable("activities");
        });

        modelBuilder.Entity("ActivityManagement.Infrastructure.Audit.AuditLog", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<string>("Action")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("action");

            b.Property<Guid?>("CorrelationId")
                .HasColumnType("uuid")
                .HasColumnName("correlation_id");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<string>("DeltaJson")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("delta_json");

            b.Property<Guid>("EntityId")
                .HasColumnType("uuid")
                .HasColumnName("entity_id");

            b.Property<string>("EntityType")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("entity_type");

            b.Property<Guid>("TenantId")
                .HasColumnType("uuid")
                .HasColumnName("tenant_id");

            b.Property<Guid?>("UserId")
                .HasColumnType("uuid")
                .HasColumnName("user_id");

            b.HasKey("Id");

            b.HasIndex("TenantId", "EntityType", "EntityId")
                .HasDatabaseName("idx_audit_logs_tenant_entity");

            b.ToTable("audit_logs");
        });

        modelBuilder.Entity("ActivityManagement.Infrastructure.Outbox.OutboxMessage", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<string>("DedupKey")
                .HasColumnType("text")
                .HasColumnName("dedup_key");

            b.Property<string>("EventType")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("event_type");

            b.Property<DateTimeOffset>("OccurredAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("occurred_at");

            b.Property<string>("PayloadJson")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("payload_json");

            b.Property<DateTimeOffset?>("PublishedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("published_at");

            b.Property<Guid>("TenantId")
                .HasColumnType("uuid")
                .HasColumnName("tenant_id");

            b.HasKey("Id");

            b.HasIndex("PublishedAt")
                .HasFilter("published_at IS NULL")
                .HasDatabaseName("idx_outbox_unpublished");

            b.HasIndex("EventType", "DedupKey")
                .IsUnique()
                .HasFilter("dedup_key IS NOT NULL")
                .HasDatabaseName("uq_outbox_dedup");

            b.ToTable("outbox_messages");
        });

        // ADR-0006: digest_action_tokens é owned pelo digest (BC-06).
        // Mapeada com ExcludeFromMigrations — o activity-management é somente consumidor.
        // token_hash: BYTEA NOT NULL (SHA-256, 32 bytes).
        // activity_id: UUID NOT NULL (referência lógica sem FK física — DD-001).
        modelBuilder.Entity("ActivityManagement.Infrastructure.Tokens.DigestActionToken", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<string>("Action")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)")
                .HasColumnName("action");

            b.Property<Guid>("ActivityId")
                .HasColumnType("uuid")
                .HasColumnName("activity_id");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<DateTimeOffset>("ExpiresAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("expires_at");

            b.Property<Guid>("TenantId")
                .HasColumnType("uuid")
                .HasColumnName("tenant_id");

            b.Property<byte[]>("TokenHash")
                .IsRequired()
                .HasColumnType("bytea")
                .HasColumnName("token_hash");

            b.Property<DateTimeOffset?>("UsedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("used_at");

            b.Property<Guid>("UserId")
                .HasColumnType("uuid")
                .HasColumnName("user_id");

            b.HasKey("Id");

            b.HasIndex("TokenHash")
                .IsUnique()
                .HasDatabaseName("uq_digest_action_tokens_hash");

            b.ToTable("digest_action_tokens", t => t.ExcludeFromMigrations());
        });
#pragma warning restore 612, 618
    }
}
