// <auto-generated />
using System;
using GoalForecast.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoalForecast.Infrastructure.Persistence.Migrations;

[DbContext(typeof(GoalForecastDbContext))]
partial class GoalForecastDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.6")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("GoalForecast.Domain.Aggregates.Goal", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<Guid>("TenantId")
                .HasColumnType("uuid")
                .HasColumnName("tenant_id");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.Property<long>("ValorMeta")
                .HasColumnType("bigint")
                .HasColumnName("valor_meta");

            b.HasKey("Id");

            b.HasIndex("TenantId")
                .HasDatabaseName("ix_goals_tenant");

            b.ToTable("goals");

            b.OwnsOne("GoalForecast.Domain.ValueObjects.GoalScope", "Scope", b1 =>
            {
                b1.Property<Guid>("GoalId")
                    .HasColumnType("uuid");

                b1.Property<Guid>("BuId")
                    .HasColumnType("uuid")
                    .HasColumnName("bu_id");

                b1.Property<Guid?>("OwnerId")
                    .HasColumnType("uuid")
                    .HasColumnName("owner_id");

                b1.HasKey("GoalId");
                b1.ToTable("goals");
                b1.WithOwner().HasForeignKey("GoalId");
            });

            b.OwnsOne("GoalForecast.Domain.ValueObjects.GoalPeriod", "Period", b1 =>
            {
                b1.Property<Guid>("GoalId")
                    .HasColumnType("uuid");

                b1.Property<short>("Month")
                    .HasColumnType("smallint")
                    .HasColumnName("month");

                b1.Property<short>("Year")
                    .HasColumnType("smallint")
                    .HasColumnName("year");

                b1.HasKey("GoalId");
                b1.ToTable("goals");
                b1.WithOwner().HasForeignKey("GoalId");
            });

            b.Navigation("Period").IsRequired();
            b.Navigation("Scope").IsRequired();
        });
#pragma warning restore 612, 618
    }
}
