// <auto-generated />
// Snapshot mínimo para satisfazer EF Core migrations (modelo simplificado).
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using TenantAdministration.Infrastructure.Persistence;

#pragma warning disable CS8618

[assembly: DbContext(typeof(TenantAdministrationDbContext))]

namespace TenantAdministration.Infrastructure.Persistence.Migrations;

[DbContext(typeof(TenantAdministrationDbContext))]
partial class TenantAdministrationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        // Snapshot gerado para suporte ao mecanismo de migrations.
        // O schema real é definido em InitialSchema.cs via SQL explícito.
    }
}
