// <auto-generated />
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using PartnerManagement.Infrastructure.Persistence;

namespace PartnerManagement.Infrastructure.Persistence.Migrations;

[DbContext(typeof(PartnerManagementDbContext))]
partial class PartnerManagementDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.6")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.Entity("PartnerManagement.Domain.Partners.Partner", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<bool>("Status")
                .HasColumnType("boolean")
                .HasColumnName("active");

            b.Property<string>("ContactEmail")
                .HasColumnType("text")
                .HasColumnName("contact_email");

            b.Property<string>("ContactPhone")
                .HasColumnType("text")
                .HasColumnName("contact_phone");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<Guid>("CreatedBy")
                .HasColumnType("uuid")
                .HasColumnName("created_by");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("character varying(255)")
                .HasColumnName("name");

            b.Property<string>("Notes")
                .HasColumnType("text")
                .HasColumnName("notes");

            b.Property<string>("Role")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("partner_type");

            b.Property<Guid>("TenantId")
                .HasColumnType("uuid")
                .HasColumnName("tenant_id");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.Property<Guid>("UpdatedBy")
                .HasColumnType("uuid")
                .HasColumnName("updated_by");

            b.HasKey("Id");

            b.ToTable("partners");

            b.OwnsOne("PartnerManagement.Domain.Partners.ValueObjects.CommissionDefaults", "CommissionDefaults", b1 =>
            {
                b1.Property<Guid>("PartnerId").HasColumnType("uuid");
                b1.Property<decimal>("PctSetup").HasPrecision(5, 2).HasColumnType("numeric(5,2)").HasColumnName("pct_setup");
                b1.Property<decimal>("PctRecorrente").HasPrecision(5, 2).HasColumnType("numeric(5,2)").HasColumnName("pct_recorrente");
                b1.HasKey("PartnerId");
                b1.ToTable("partners");
                b1.WithOwner().HasForeignKey("PartnerId");
            });

            b.Navigation("CommissionDefaults").IsRequired();
        });

        modelBuilder.Entity("PartnerManagement.Infrastructure.Outbox.OutboxMessage", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
            b.Property<string>("EventType").IsRequired().HasColumnType("text").HasColumnName("event_type");
            b.Property<DateTimeOffset>("OccurredAt").HasColumnType("timestamp with time zone").HasColumnName("occurred_at");
            b.Property<string>("PayloadJson").IsRequired().HasColumnType("jsonb").HasColumnName("payload_json");
            b.Property<DateTimeOffset>("PublishedAt").HasColumnType("timestamp with time zone").HasColumnName("published_at");
            b.Property<Guid>("TenantId").HasColumnType("uuid").HasColumnName("tenant_id");
            b.HasKey("Id");
            b.ToTable("outbox_messages");
        });

        modelBuilder.Entity("PartnerManagement.Infrastructure.Idempotency.IdempotencyKey", b =>
        {
            b.Property<Guid>("TenantId").HasColumnType("uuid").HasColumnName("tenant_id");
            b.Property<string>("Key").IsRequired().HasColumnType("text").HasColumnName("idempotency_key");
            b.Property<string>("RequestHash").IsRequired().HasColumnType("text").HasColumnName("request_hash");
            b.Property<Guid>("ResponseRef").HasColumnType("uuid").HasColumnName("response_ref");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
            b.HasKey("TenantId", "Key");
            b.ToTable("idempotency_keys");
        });
#pragma warning restore 612, 618
    }
}
