// <auto-generated />
using System;
using Digest.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Digest.Infrastructure.Persistence.Migrations;

[DbContext(typeof(DigestDbContext))]
[Migration("20260615000000_AddDigestTenantSettings")]
partial class AddDigestTenantSettings
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.6")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.Entity("Digest.Domain.Entities.EmailDigestLog", b =>
        {
            b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
            b.Property<Guid>("TenantId").HasColumnName("tenant_id").HasColumnType("uuid").IsRequired();
            b.Property<Guid>("UserId").HasColumnName("user_id").HasColumnType("uuid").IsRequired();
            b.Property<string>("Status").HasColumnName("status").HasColumnType("varchar(20)").IsRequired();
            b.HasKey("Id");
            b.ToTable("email_digest_logs");
        });

        modelBuilder.Entity("Digest.Domain.Entities.DigestActionToken", b =>
        {
            b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
            b.Property<Guid>("TenantId").HasColumnName("tenant_id").HasColumnType("uuid").IsRequired();
            b.Property<string>("Action").HasColumnName("action").HasColumnType("varchar(20)").IsRequired();
            b.HasKey("Id");
            b.ToTable("digest_action_tokens");
        });

        modelBuilder.Entity("Digest.Infrastructure.Messaging.OutboxMessage", b =>
        {
            b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
            b.HasKey("Id");
            b.ToTable("outbox_messages");
        });

        modelBuilder.Entity("Digest.Infrastructure.Persistence.DigestTenantSettings", b =>
        {
            b.Property<Guid>("TenantId").HasColumnName("tenant_id").HasColumnType("uuid");
            b.Property<int>("ActionTokenTtlHours").HasColumnName("action_token_ttl_hours").HasColumnType("integer").IsRequired();
            b.Property<DateTimeOffset>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamptz").IsRequired();
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnName("updated_at").HasColumnType("timestamptz").IsRequired();
            b.HasKey("TenantId");
            b.ToTable("digest_tenant_settings");
        });
#pragma warning restore 612, 618
    }
}
