// <auto-generated />
using Digest.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Digest.Infrastructure.Persistence.Migrations;

[DbContext(typeof(DigestDbContext))]
partial class DigestDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.6")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.Entity("Digest.Domain.Entities.EmailDigestLog", b =>
        {
            b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
            b.Property<Guid>("TenantId").HasColumnName("tenant_id").HasColumnType("uuid").IsRequired();
            b.Property<Guid>("UserId").HasColumnName("user_id").HasColumnType("uuid").IsRequired();
            b.Property<string>("Status").HasColumnName("status").HasColumnType("varchar(20)").IsRequired();
            b.HasKey("Id");
            b.ToTable("email_digest_logs");
        });

        modelBuilder.Entity("Digest.Domain.Entities.DigestActionToken", b =>
        {
            b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
            b.Property<Guid>("TenantId").HasColumnName("tenant_id").HasColumnType("uuid").IsRequired();
            b.Property<string>("Action").HasColumnName("action").HasColumnType("varchar(20)").IsRequired();
            b.HasKey("Id");
            b.ToTable("digest_action_tokens");
        });

        modelBuilder.Entity("Digest.Infrastructure.Messaging.OutboxMessage", b =>
        {
            b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
            b.HasKey("Id");
            b.ToTable("outbox_messages");
        });
#pragma warning restore 612, 618
    }
}
