// <auto-generated />
// Snapshot gerado para uso pelo EF Core migrations.
// Atualizar quando houver nova migration.
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using OpportunityPipeline.Infrastructure.Persistence;

#nullable disable

namespace OpportunityPipeline.Infrastructure.Persistence.Migrations;

[DbContext(typeof(OpportunityDbContext))]
partial class OpportunityDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.6")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        // Snapshot mínimo — o schema real é gerenciado pelas migrations SQL manuais.
        // As entidades são mapeadas pelas configurações em Configurations/.
#pragma warning restore 612, 618
    }
}
